akka {
    javasdk {
        components {
            event-sourced-entity=[
                "com.hrushi.firstakka.domain.entities.CustomerEntity"
            ]
            http-endpoint=[
                "com.hrushi.firstakka.api.CustomerEndpoint",
                "com.hrushi.firstakka.api.PreferencesEndpoint"
            ]
            key-value-entity=[
                "com.hrushi.firstakka.domain.entities.CustomerPreferencesEntity"
            ]
            view=[
                "com.hrushi.firstakka.views.CustomerView"
            ]
        }
    }
}
